### PR TITLE
Fix high cpu usage and low throughput

### PR DESCRIPTION
**Pull request by DarrenTsung**
When testing against high volume of requests, the current implementation in `master` does poorly.

To fix this:
* Make reading the `Body` of the `Response` optional. 
* Update to hyper 0.12 - this lowered the overall poll count && cpu usage.
* Making DNS resolution in the HttpConnector blocking so redundant resolutions do not occur.

Some benchmarks on my machine (running `time` and sending 2000 requests):

Previous implementation before update (using forked Hyper 0.8):
```
cargo test lots_of_get_single_worker  1.63s user 0.75s system 3% cpu 1:01.42 total
cargo test lots_of_get_single_worker  1.73s user 0.78s system 4% cpu 1:01.28 total
```

Note that it took very little process time. However the total actual time before the responses finish is very slow for some reason.

Current implementation on master:
```
cargo test a_ton_of_gets_single_worker  174.11s user 3.12s system 323% cpu 54.739 total
cargo test a_ton_of_gets_single_worker  150.86s user 2.51s system 337% cpu 45.462 total
cargo test a_ton_of_gets_single_worker  131.68s user 2.09s system 331% cpu 40.413 total
cargo test a_ton_of_gets_single_worker  141.08s user 2.30s system 335% cpu 42.755 total
```

New implementation:
```
cargo test a_ton_of_gets_single_worker -- --nocapture  26.46s user 1.44s system 175% cpu 15.936 total
cargo test a_ton_of_gets_single_worker -- --nocapture  29.30s user 1.52s system 220% cpu 13.986 total
cargo test a_ton_of_gets_single_worker -- --nocapture  20.77s user 1.36s system 97% cpu 22.638 total
cargo test a_ton_of_gets_single_worker -- --nocapture  48.93s user 1.50s system 229% cpu 21.987 total
```

It doesn't use a little process time as the previous implementation, but you can clearly see that it's a huge improvement. The total actual time for the responses to finish is much faster as well.

### CODE REVIEW

**Comment by jwilm** [comment]
Exciting to see progress here!

Synchronous DNS resolution is pretty much a non-starter at the volume of requests we're running. It would block the event loop and not make forward progress for that period.

Regarding higher CPU time, it seems pretty significant. Is it possible that we are polling a big collection or something like that in our implementation? Have you done any profiling here? It would be interesting to see how often our own poll method is called and get an average over number of transactions.

**Comment by DarrenTsung** [comment]
Will reply with more details later, but good catch about the synchronous
DNS. Actually what we're doing instead of spawning a fully asynchronous
ip_loopup for every request is spawning it on a cpu threadpool that runs
the request synchronously so that it avoids expensive calculations for the
same DNS lookup running in parallel (from the cachegrind report)

Planning to look into profiling it further now that I'm done converting all
the code to use hyper 0.12!

**Comment by jwilm** [comment]
If trust DNS was a problem, let's go back to c-ares. We actually used to get `SIGILL` in production when using hyper's built-in DNS resolution -- we moved away for good reason.

**Comment by DarrenTsung** [comment]
It doesn't seem to be trust-DNS, using the built-in implementation takes around the same time. Using c-ares actually increases the amount of cpu usage / total time as it seems to fail the requests more often. 

It seems like some of the changes pulled in from updating hyper may be behind the increase of cpu usage. I'm going to run another profiling pass to see if there's anything obvious and check this version integrated with `onepush` to compare the difference.

**Comment by DarrenTsung** [comment]
After porting this to onepush, I did some more testing on the old commit. See `origin/benchmark-old` for the exact test I used. Turns out that on higher transaction counts hyper starts to break down and start failing more requests and the old commit was ignoring that. I adjusted both tests to run a lower amount of requests (600) so they would mostly complete all the requests successfully.

`benchmark-old` branch:
```
root@c430ddef97aa:/hyper-client-pool# hyperfine --warmup 3 '/hyper-client-pool-target/target/release/deps/hyper_client_pool-51f90383b727a7da lots_of_get'
Benchmark #1: /hyper-client-pool-target/target/release/deps/hyper_client_pool-51f90383b727a7da lots_of_get
  Time (mean ± σ):      6.302 s ±  2.130 s    [User: 401.0 ms, System: 295.0 ms]
  Range (min … max):    5.526 s … 12.346 s

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

`cpu-usage` branch:
```
root@c430ddef97aa:/hyper-client-pool# hyperfine --warmup 3 '/hyper-client-pool-target/target/release/deps/lib-f48a956b9a3620cc ton_of_gets'
Benchmark #1: /hyper-client-pool-target/target/release/deps/lib-f48a956b9a3620cc ton_of_gets
  Time (mean ± σ):      2.928 s ±  2.570 s    [User: 863.0 ms, System: 247.0 ms]
  Range (min … max):    1.467 s … 10.097 s
```

Seems like there are still outliers in both test runs, but the user / system usage is much closer! 

Everything works now with `onepush`, but I need to investigate some occasional panics in the dns threads with the new implementation (futures::spawn panicking with [SpawnError::is_shutdown](https://docs.rs/tokio/0.1.7/tokio/executor/struct.SpawnError.html)).

**Comment by DarrenTsung** [comment]
Okay I spent some time fixing the panicking in trust-dns, but in the end trust-dns was just too slow. I switched back to the c-ares branch and found that it was much more comparable to the previous implementation.

`benchmark-old` results:
```
root@54e5b726bf9a:/hyper-client-pool# hyperfine --warmup 3 '/hyper-client-pool-target/target/release/deps/hyper_client_pool-51f90383b727a7da lots_of_get'
Benchmark #1: /hyper-client-pool-target/target/release/deps/hyper_client_pool-51f90383b727a7da lots_of_get

  Time (mean ± σ):      3.576 s ±  1.739 s    [User: 46.0 ms, System: 145.0 ms]
  Range (min … max):    1.531 s …  5.183 s
```

`hyper-0.12-c-ares`
```
Benchmark #1: /hyper-client-pool-target/target/release/deps/lib-2c3ff674afeb087f ton

  Time (mean ± σ):      4.086 s ±  4.219 s    [User: 80.0 ms, System: 199.0 ms]
  Range (min … max):    1.540 s … 15.158 s

  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

You can see that c-ares had some outliers, but that was sporadic and seen with the previous implementation as well. 

I think this is good to go! @jwilm @coder543 let me know what you guys think of the latest changes.

**Comment by DarrenTsung** [comment]
Closing this to review cpu-usage-final which includes the fix for socket thrashing in `hyper`.

**Pull request closed without merging**
